### ISSUE TITLE
Problem Building Frontend Container

### ISSUE THREAD

**Issue by X8ETr1x** [target/strelka#119]
**Describe the bug**
The frontend Docker container build fails due to a type error in the main.go file.

**Steps to reproduce**
1. Run `docker-compose -f build/docker-compose.yaml up`
2. See error 
```
# github.com/target/strelka/src/go/cmd/strelka-frontend`
./main.go:146:25: cannot use &redis.Z literal (type *redis.Z) as type redis.Z in argument to s.coordinator.cli.cmdable.ZAdd
```

**Expected behavior**
Successful build of the Strelka frontend container.

**Release**
 - Commit ID: 669fd86

**Additional context**
Linux: SLES 15 4.12.14-197.15-default
Docker version: 19.03.1
Go version: 1.13.4 linux/amd64

This seems to be similar to https://github.com/target/strelka/issues/71.

Please let me know if you need any additional information.

**Comment by phutelmyer** [comment]
I believe this issue was fixed per https://github.com/target/strelka/commit/1b4f8c6dc4737b497b662cac648d491ed1e43b63#diff-299a77632afe8120ec80e4446141b1eab3bb86a6b75049548043c5ce2839c813
Thank you for opening this issue and if you happen to have a similar issue - please let me know and I'll take a look. Thanks!
