### ISSUE TITLE
[Feature Request] Add scanner support for 7z archives

### ISSUE THREAD

**Issue by aidenmitchell** [target/strelka#235]
cc @rw-access

**Is your feature request related to a problem? Please describe.**
It seems that Strelka doesn't have the ability to scan 7z archives, in the same way that it can for zip archives. This leads to some uncertainly when scanning 7z archives, specifically the ability to list files inside archives.

**Describe the solution you'd like**
Support for 7z archives similar to current zip archive support (zip scanner: https://github.com/target/strelka/blob/master/src/python/strelka/scanners/scan_zip.py)

**Describe alternatives you've considered**
Cloning and refactoring the existing zip scanner, however my Python skills are not that advanced...

Thank you for your consideration!

**Comment by phutelmyer** [comment]
Hi @aidenmitchell - Thanks for the request.
You're correct that ScanZip currently does not support 7z metadata collection and extraction, however ScanLibarchive does. If you have that scanner enabled, files in an unencrypted 7z will be extracted through the Strelka pipeline.

ScanLibarchive does _not_ support the same metadata extraction, though, so your point still stands.

I may be able to add that in, if you're looking for metadata collection rather than extraction.

**Comment by aidenmitchell** [comment]
We're specifically looking for file names inside encrypted 7z archives, something the ScanZip scanner supports (from what I can tell.) If that's a feature you can add, that would be great!

**Comment by phutelmyer** [comment]
7z support added for VHD file scanning per #243 - could rebake ScanZip to include that functionality (or create an alternative Scan7zip)

**Comment by phutelmyer** [comment]
#258 includes a reference to perhaps converting `ScanZip` to use `7z` rather than `zipfile` module, which would bring functionality needed to close this ticket.
