### ISSUE TITLE
scan_pkcs7 API mismatch

### ISSUE THREAD

**Issue by dcode** [target/strelka#63]
**Describe the bug**
I used the steps in the documentation to build the Dockerfile this morning (checked out 4a97567) and scanned a test file that has a good load of filth in it ([link](https://drive.google.com/file/d/1kWmwNQ5W0o7TFgopa8I2pMrvUYQufrku/view?usp=sharing) - **WARNING** actually contains malware, but you'd have to go out of your way to trigger it (i.e. not executable, doesn't have executable file extensions, etc) )

The file contains an x509 cert, some vt scan data, some archive formats, and some OS binaries.

**Steps to reproduce**
1. Build and run the Dockerfile according to the directions
2. Submit the linked zip archive
3. See the PKCS object error

```
2019-05-13 12:27:02 - [ERROR] root [objects.scan_wrapper]: ScanPkcs7: exception while scanning file with hash f0bcf8f9fde7c6b737ae48761c7298e98c2412576ef0d07474df3211e309adf2 and uid 238f900f-34cc-43a7-881d-bce61c528089 (see traceback below)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/strelka-0.99-py3.6.egg/server/objects.py", line 513, in scan_wrapper
    self.scan(file_object, options)
  File "/usr/local/lib/python3.6/dist-packages/strelka-0.99-py3.6.egg/server/scanners/scan_pkcs7.py", line 20, in scan
    pkcs7_certificates = pkcs7.get_certificates()
AttributeError: 'PKCS7' object has no attribute 'get_certificates'
```

**Expected behavior**
I expected that Strelka would be able to handle the certificate errors, or at least die gracefully.

**Server and project version**
 - OS: Bionic via Docker, run on Mac
 - Commit Hash: 4a97567730e8ec5a8b3870360f032c915d3812be

**Additional context**
Looks like the PKCS7 API changed, is all.

**Comment by jshlbrd** [comment]
Thanks, I’ll look into this soon. I was planning a longer-term migration to m2crypto (it has Python3 support now), but if this is a simple fix then I can take care of this first.

**Comment by jshlbrd** [comment]
@dcode looks like I can't download that file, Google is clever enough to do this:
```
Sorry, this file is infected with a virus

Only the owner is allowed to download infected files.
```

I'd suggest joining our Slack channel, we should be able to share files safely there.

**Comment by jshlbrd** [comment]
For the sake of testing the issue, I cloned the repository at the same commit and did a scan on Wireshark's 64-bit EXE (https://2.na.dl.wireshark.org/win64/Wireshark-win64-3.0.1.exe) -- this is a file that I know has worked in the past for MZ --> PKCS7 --> X509 parsing. 

The problem immediately became apparent -- when we transitioned to a pip requirements.txt file, we mistakenly added the main pyopenssl package instead of a forked version that includes `get_certificates`. I'll be merging a PR momentarily that resolves this.

To add onto this, I want to address your concerns regarding the expected behavior. I did confirm that Strelka is behaving as designed in this scenario -- in this case, the package not having the `get_certificates` function is an unhandled error which Strelka treats as a generic exception. This achieves two things -- it prevents Strelka from crashing unnecessarily and it ensures that the user knows what caused the exception so that it can be addressed if needed. Here's an example of scan results for the PKCS7 file with the 'bad' pyopenssl package:
```json
    {
      "flags": [
        "ScanYara::compiling_error"
      ],
      "flavors": {
        "mime": [
          "application/octet-stream"
        ],
        "yara": [
          "pkcs7_file"
        ]
      },
      "entropyMetadata": {
        "entropy": 7.3315157217990965
      },
      "hashMetadata": {
        "md5": "491af2cc04942fcbb250f83db268d78b",
        "sha1": "c5bad20e6fa1928c73a3ccd08edf02cad3987bae",
        "sha256": "55acef7854e3654a49185d30fc5e77a685d98df1611ae122dc329461222de71e",
        "ssdeep": "192:qMDWpH0V3E7an7+nYe+PjPn9DWpH0V3E7aFtfH0JOqsmVgz28WhBqjAiZI:TDGu3zn7+nYPLn9DGu3zFt8JN77hhOq"
      },
      "headerMetadata": {
        "header": "0�4�\u0006\t*�H��\r\u0001\u0007\u0002��4�0�4�\u0002\u0001\u00011\u000b0\t\u0006\u0005+\u000e\u0003\u0002\u001a\u0005\u00000L\u0006\n+\u0006\u0001\u0004\u0001�7"
      },
      "pkcs7Metadata": {
        "total": {
          "certificates": 0,
          "extracted": 0
        },
        "cryptoType": "der"
      },
      "selfMetadata": {
        "filename": "ScanPe::digital_signature",
        "depth": 1,
        "uid": "550bd283-85d1-48d3-a503-49cfdb7bac00",
        "parentUid": "ce27b2a1-1226-42a2-909b-d3d7318800f9",
        "rootUid": "ce27b2a1-1226-42a2-909b-d3d7318800f9",
        "hash": "55acef7854e3654a49185d30fc5e77a685d98df1611ae122dc329461222de71e",
        "parentHash": "80e9bdfcb3bfb3800c202efcdfbb286a2b89d0bf2b8d94f2727d117b0013c821",
        "rootHash": "80e9bdfcb3bfb3800c202efcdfbb286a2b89d0bf2b8d94f2727d117b0013c821",
        "source": "ScanPe",
        "scannerList": [
          "ScanEntropy",
          "ScanHash",
          "ScanHeader",
          "ScanPkcs7",
          "ScanSelf",
          "ScanYara"
        ],
        "size": 13472
      }
    }
```

The important thing here is that Strelka still produced some event data about the file even though it did not produce all of the data.

**Comment by dcode** [comment]
Thanks @jshlbrd.. that all makes sense..thanks for the prompt look!

**Comment by jshlbrd** [comment]
@dcode no problem! FYSA, between the opening of this issue and now the Strelka repository migrated from using ZeroMQ to using gRPC -- if you were working on a deployment, you may want to revisit the new documentation. I'm also hoping to get m2crypto support in within the next month or so.
