### ISSUE TITLE
support multiple directories in dirstream

### ISSUE THREAD

**Issue by zoomequipd** [target/strelka#8]
**Is your feature request related to a problem? Please describe.**
I have an existing process which has files extracted to multiple directories.  I would like all of the directories to be monitored for new files and have them sent to the broker without running multiple instances of dirstream.

**Describe the solution you'd like**
Allow for multiple directories to be configured in the dirstream config.  Ideally, each configured directory could have it's own unique configurations (meta_separator, delete_files, etc).  Then monitor as each directory as configured and send files to the broker.

**Describe alternatives you've considered**
I've considered running multiple dirstream processes with different configurations, one for each directory to monitor. 

**Additional context**
N/A

**Comment by jshlbrd** [comment]
I think this is a reasonable idea -- based on the request, my recommendation is to update the dirstream utility to handle multiple directories with shared settings _and_ multiple directories with unique settings. 

I've marked this as a good first issue because adding this functionality doesn't require a deep understanding of the project, but it would require careful thought for redesigning the dirstream config file (i.e. make it so the user can easily understand if dirstream is configured to monitor one directory, multiple directories with shared settings, or multiple directories with unique settings) and an understanding of coding reusable functions. This code block is where most effort would need to be placed because it is currently written to handle only one directory: https://github.com/target/strelka/blob/master/strelka_dirstream.py#L239-L269

**Comment by jshlbrd** [comment]
As a result of unrelated changes to dirstream, this was resolved in https://github.com/target/strelka/pull/17.
